[env:teensy40]
platform = teensy
board = teensy40
framework = arduino
monitor_speed = 9600
extra_scripts =
  scripts/disable_audio_adc.py
build_flags =
  -D USB_AUDIO
  -D AUDIO_BLOCK_SAMPLES=128
  -Iinclude
  -include Arduino.h
  -include audio_register_compat.h
lib_deps =
  paulstoffregen/Audio@^1.3
  adafruit/Adafruit SSD1306@^2.5.11
